language: node_js
node_js:
  - 14
  - 12
  - 10
install:
  - npm install
  - npm install -g codecov
jobs:
  include:
    - stage: test
      script: bash ./scripts/test.sh
    - stage: deploy
      if: branch = master
      script: bash ./scripts/deploy.sh